# Generated by Django 4.2.13 on 2024-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcard',
            name='card_id',
            field=models.IntegerField(unique=True),
        ),
    ]
